version: '3.8'
services:
  dataBase:
    image: postgres:15
    environment:
      POSTGRES_DB: "sber"
      POSTGRES_USER: "sber"
      POSTGRES_PASSWORD: "passWORD"
    ports:
      - "5431:5432"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://${HOST}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  api:
    build: ./backend
    ports:
      - '8888:8888'
    environment:
      HOST: ${HOST}
    depends_on:
      - dataBase
      - kafka
    external_links:
      - dataBase
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ui:
    build: ./ui
    ports:
      - '3006:3005'
    volumes:
      - ./ui/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ui/public/index.html:/usr/share/nginx/html/index.html
      - ./ui/public/css:/usr/share/nginx/html/css
    restart: always
